version: '3.1'

services:


  Virtual-white-board-database:
    container_name: 'JTW-DB'
    image: mariadb:latest
    hostname: database
    restart: always
    ports:
      - 3320:3306
    environment:
      MYSQL_DATABASE: JWT-DB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin